//! Tauri-independent application modules shared by native TieZ frontends.

pub mod ai;
pub mod backup;
pub mod clipboard_capture;
pub mod clipboard_history;
pub mod cloud_sync_protocol;
pub mod cloud_sync_runner;
pub mod cloud_sync_settings;
pub mod cloud_sync_sqlite;
pub mod cloud_sync_webdav;
pub mod content_identity;
pub mod content_opening;
pub mod data_directory;
pub mod database_bootstrap;
pub mod database_migrations;
pub mod database_mutation;
pub mod encryption;
pub mod emoji_favorites;
pub mod file_transfer;
pub mod image_analysis;
pub mod native_settings;
pub mod paste_coordinator;
pub mod privacy;
pub mod production_history;
pub mod production_mutation;
pub mod runtime_instance;
pub mod tag_catalog;
pub mod ui_lifecycle;
